import { StyleSheet } from "react-native";


const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0a0a1a",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#222",
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "500",
    color: "#fff",
  },
  scrollView: {
    flex: 1,
  },
  mediaContainer: {
    width: "100%",
    height: 250,
    backgroundColor: "#111",
    position: "relative",
  },
  uploadPlaceholder: {
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  uploadText: {
    color: "#666",
    marginTop: 8,
  },
  mediaPreviewContainer: {
    width: "100%",
    height: "100%",
    position: "relative",
  },
  mediaPreview: {
    width: "100%",
    height: "100%",
  },
  videoPreview: {
    width: "100%",
    height: "100%",
    backgroundColor: "#222",
    justifyContent: "center",
    alignItems: "center",
  },
  audioPreview: {
    width: "100%",
    height: "100%",
    backgroundColor: "#222",
    justifyContent: "center",
    alignItems: "center",
  },
  previewText: {
    color: "#fff",
    marginTop: 8,
  },
  removeButton: {
    position: "absolute",
    top: 8,
    right: 8,
    backgroundColor: "rgba(255, 0, 0, 0.7)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 4,
  },
  removeButtonText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "500",
  },
  paginationDots: {
    position: "absolute",
    bottom: 8,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "center",
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#fff",
    marginHorizontal: 2,
  },
  activeDot: {
    backgroundColor: "#3b82f6",
  },
  formContainer: {
    padding: 16,
  },
  fieldContainer: {
    marginBottom: 24,
  },
  label: {
    fontSize: 14,
    fontWeight: "500",
    color: "#fff",
    marginBottom: 8,
  },
  inputContainer: {
    position: "relative",
    backgroundColor: "#0f1123",
    borderWidth: 1,
    borderColor: "#333",
    borderRadius: 8,
  },
  input: {
    color: "#fff",
    padding: 12,
    paddingRight: 50,
  },
  textareaContainer: {
    position: "relative",
    backgroundColor: "#0f1123",
    borderWidth: 1,
    borderColor: "#333",
    borderRadius: 8,
    minHeight: 100,
  },
  textarea: {
    color: "#fff",
    padding: 12,
    paddingRight: 50,
    textAlignVertical: "top",
    minHeight: 100,
  },
  charCount: {
    position: "absolute",
    bottom: 8,
    right: 12,
    fontSize: 12,
    color: "#666",
  },
  tagsContainer: {
    backgroundColor: "#0f1123",
    borderWidth: 1,
    borderColor: "#333",
    borderRadius: 8,
    padding: 12,
  },
  tagsList: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 8,
  },
  tag: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#333",
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginRight: 8,
    marginBottom: 8,
  },
  tagText: {
    color: "#fff",
    fontSize: 12,
  },
  tagRemove: {
    color: "#999",
    fontSize: 16,
    marginLeft: 4,
  },
  tagInputContainer: {
    marginTop: 4,
  },
  tagInput: {
    color: "#fff",
    padding: 0,
    height: 32,
  },
  scheduleContainer: {
    backgroundColor: "#0f1123",
    borderWidth: 1,
    borderColor: "#333",
    borderRadius: 8,
    padding: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  timeContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  scheduleText: {
    color: "#fff",
    marginHorizontal: 8,
  },
  visibilitySelector: {
    backgroundColor: "#0f1123",
    borderWidth: 1,
    borderColor: "#333",
    borderRadius: 8,
    padding: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  visibilityContent: {
    flexDirection: "row",
    alignItems: "center",
  },
  visibilityIcon: {
    marginRight: 8,
  },
  visibilityText: {
    color: "#fff",
  },
  buttonContainer: {
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: "#222",
  },
  uploadButton: {
    backgroundColor: "#3b82f6",
    borderRadius: 8,
    padding: 16,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
  },
  uploadButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "500",
  },
  loader: {
    marginLeft: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#0f1123",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    padding: 16,
  },
  visibilityModalContent: {
    backgroundColor: "#0f1123",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    padding: 16,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "500",
    color: "#fff",
  },
  mediaTypeContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 16,
  },
  mediaTypeOption: {
    flex: 1,
    backgroundColor: "#1a1b2e",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#333",
    height: 100,
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: 4,
  },
  mediaTypeText: {
    color: "#fff",
    marginTop: 8,
  },
  sourceContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 16,
  },
  sourceOption: {
    flex: 1,
    backgroundColor: "#1a1b2e",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#333",
    height: 100,
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: 4,
  },
  sourceText: {
    color: "#fff",
    marginTop: 8,
  },
  visibilityOption: {
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#222",
  },
  visibilityOptionText: {
    color: "#fff",
    fontSize: 16,
  },
});
export default styles;
