export default {
  WHITE: '#fff',
  BLACK: '#000',
  ERROR_TEXT_COLOR: '#FF3B30',
  INPUT_FIELD_BG_COLOR: '#FFFBF4',
  INPUT_FIELD_PLACEHODER_COLOR: '#999999',
  COLOR_YELLOW: '#E1AD52',
  INACTIVE_TAB_COLOR: '#C3C3C3',
  TEXT_LOGOUT_COLOR: '#FF3B30',
  TEXT_RATING_COLOR: '#4CAF50',
  BG_COLOR_MODAL: '#F4F4F4',
  APP_TEXT_COLOR: '#151F25',
  APP_TEXT_LIGHT_COLOR: '#717171',
  INPUT_FIELD_ACTIVE_BG_COLOR: '#FCFCFC',
  INPUT_FIELD_IN_ACTIVE_BG_COLOR: '#F4F4F4',

  //----NewColor----//
  APP_TEXT_BLUE_COLOR: '#2E92EF',
  BACKGOUND: '#01081A',
  BUTTON_BACKGROUND: "#0360D2"


};
